# Generated by Django 2.2.7 on 2019-11-26 02:46

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duke_netid',
            field=models.CharField(max_length=8, blank=True, null=True),
        ),
    ]
