# Generated by Django 2.2.7 on 2019-11-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191126_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='netid',
        ),
    ]
